server:
  port: "8095"

database:
  host: "localhost"
  port: "3306"
  user: "my_user"
  password: "Hellomysqlostk1-"
  dbname: "portaldata"

data_path: "/var/www/api.ostk.ru/data"
api_key: "f428fbc16a97b9e2a55717bd34e97537ec34cb8c04a5f32eeb4e88c9ee998a53"
