redis:
  # Адрес Redis сервера
  addr: "127.0.0.1:6379"
  
  # Пароль (пустой если не используется)
  password: ""
  
  # Номер базы данных
  db: 0
  
  # Размер пула соединений
  pool_size: 10
  
  # Таймаут соединения
  dial_timeout: "5s"
  
  # Таймаут чтения
  read_timeout: "3s"
  
  # Таймаут записи
  write_timeout: "3s"
  
  # Максимальное время простоя соединения
  idle_timeout: "5m"
  
  # Максимальное время жизни соединения
  max_conn_age: "30m"

rate_limits:
  # Минутные лимиты
  minute:
    default: 1000    # По умолчанию для всех эндпоинтов (увеличено для тестирования)
    public: 2000     # Для публичных эндпоинтов (увеличено для тестирования)
  
  # Дневные лимиты (только для GET методов)
  day:
    default: 10000   # По умолчанию для всех эндпоинтов (увеличено для тестирования)
    public: 20000    # Для публичных эндпоинтов (увеличено для тестирования)
  
  # Время жизни ключей в Redis
  ttl:
    minute: "2m"     # Минутные счетчики живут 2 минуты
    day: "25h"       # Дневные счетчики живут 25 часов
